import Head from "next/head";
import Image from "next/image";
import hero from "../public/hero.png";
import shoes from "../public/shoes.jpg";
import boat from "../public/boat.jpg";
import plate from "../public/plate.webp";
import bulb from "../public/bulb.webp";
import image from "../public/image.webp";
import woman from "../public/woman.jpg";
import {
  FaGripLines,
  FaHeartbeat,
  FaBirthdayCake,
  FaUserAstronaut,
  FaTruck,
  FaShoppingBag,
  FaWhmcs,
  FaHamburger,
  FaLightbulb,
  FaHandHoldingWater,
  FaChevronCircleRight,
  FaMapMarkerAlt,
} from "react-icons/fa";
import { BsFillTelephoneForwardFill } from "react-icons/bs";
import { RxMagnifyingGlass } from "react-icons/rx";
import {
  AiTwotoneRest,
  AiFillMail,
  AiFillFacebook,
  AiFillInstagram,
  AiFillTwitterSquare,
} from "react-icons/ai";
import { TbChartDonut } from "react-icons/tb";
import { GiWineBottle, GiStarsStack, GiHamburgerMenu } from "react-icons/gi";
import { FiMonitor } from "react-icons/fi";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" max-w-screen-2xl m-auto">
        <section>
          <div className="bg-gradient-to-tl from-indigo-800 to-violet-700">
            <nav className=" flex justify-around lg:flex lg:text-center lg:justify-between lg:mx-40 ">
              <input type={"checkbox"} id="check" className="hidden"></input>

              <h2 className="text-3xl font-bold text-white pt-7 pl-3">RELAP</h2>

              <ul className="float-right mr-10  leading-[80px] text-white font-bold uppercase rounded fixed lg:flex lg:mx-auto lg:relative h-[100vh] lg:h-0 w-[100%] lg:w-fit top-20 lg:top-0 left-[-100%] lg:left-0 transition-all duration-500 ease-in-out lg:transition-none text-center backdrop-blur-sm">
                <li className="text-gray-200 pl-10 cursor-pointer hover:scale-110 hover:tranition-all duration-300 ease-in-out ">
                  <a href="#">Features</a>
                </li>
                <li className="text-gray-200 pl-10 cursor-pointer hover:scale-110 hover:tranition-all duration-300 ease-in-out">
                  <a href="#">Works</a>
                </li>
                <li className="text-gray-200 pl-10 cursor-pointer hover:scale-110 hover:tranition-all duration-300 ease-in-out">
                  <a href="#">About</a>
                </li>
                <li className="text-gray-200 pl-10 cursor-pointer hover:scale-110 hover:tranition-all duration-300 ease-in-out">
                  <a href="#">Blog</a>
                </li>
              </ul>

              <button className="hidden text-base text-white mt-5 rounded-full ring-4 ring-slate-500 py-1 px-10 hover:scale-110 hover:tranition-all duration-300 ease-in-out lg:block lg:ml-auto">
                Contact us
              </button>

              <div className="pt-5">
                <RxMagnifyingGlass className=" text-white text-4xl mx-3 cursor-pointer hover:scale-110 hover:tranition-all duration-300 ease-in-out" />
              </div>

              <label
                for="check"
                className="float-right text-white text-3xl leading-[80px] mt-6 mr-10 lg:hidden"
              >
                <GiHamburgerMenu />
              </label>
            </nav>

            <div className="flex flex-col pb-20 lg:flex lg:flex-row lg:py-40 ">
              <div className="py-20 lg:mx-20 xl:mx-40">
                <h3 className="text-xl font-bold pl-5 lg:pl-0 text-white">
                  QUASHI ARCHITECTO
                </h3>

                <h1 className="text-5xl font-bold text-white py-10 pl-5 lg:pl-0 lg:text-6xl">
                  Beatae vitae dicta sunt
                </h1>

                <button className="text-white font-bold text-xl bg-amber-400 rounded-full ml-5 py-5 px-10 lg:mx-0 hover:scale-110 hover:tranition-all duration-300 ease-in-out">
                  Reade more
                </button>
              </div>

              <div className=" bg-gradient-to-tr from-purple-500 to-indigo-800 lg:w-96 lg:h-80 shadow-2xl shadow-slate-800 mx-5 mb-20 md:mb-20 md:mx-auto ">
                <div className=" md:w-80 md:h-80 lg:w-96 lg:h-96 lg:-ml-20 lg:mt-10">
                  <Image src={hero} width={"100%"} height={"100%"} />
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="bg-pink-50 py-20">
          <div className=" flex flex-col mx-10 lg:flex lg:flex-row lg:mx-40">
            <div className="py-5">
              <AiTwotoneRest className="text-5xl text-pink-500" />
              <h2 className="text-4xl font-bold py-3">42+</h2>
              <p className="text-gray-500 max-w-xl">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Inventore veritatis quae maxime molestiae fugit illo?
              </p>
            </div>
            <div className="py-5">
              <TbChartDonut className="text-5xl text-pink-500" />
              <h2 className="text-4xl font-bold py-3">42+</h2>
              <p className="text-gray-500 max-w-xl">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Inventore veritatis quae maxime molestiae fugit illo?
              </p>
            </div>
            <div className="py-5">
              <FaHeartbeat className="text-5xl text-pink-500" />
              <h2 className="text-4xl font-bold py-3">42+</h2>
              <p className="text-gray-500 max-w-xl">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Inventore veritatis quae maxime molestiae fugit illo?
              </p>
            </div>
            <div className="py-5">
              <FaBirthdayCake className="text-5xl text-pink-500" />
              <h2 className="text-4xl font-bold py-3">42+</h2>
              <p className="text-gray-500 max-w-xl">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Inventore veritatis quae maxime molestiae fugit illo?
              </p>
            </div>
          </div>
        </section>

        <section>
          <div className="py-20 flex flex-col lg:flex lg:flex-row lg:justify-center lg:gap-14 mx-5">
            <div className=" pb-20">
              <h3 className="font-bold text-xl">CUNSEQUATER</h3>
              <h2 className="font-bold text-3xl py-5">Quis antem vel eum</h2>
              <p className="font-medium text-gray-600 pb-10 max-w-xl">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex sunt
                quod deleniti eveniet commodi, repellat ipsa, possimus
                perferendis tempora facilis quidem? Voluptate modi eveniet
                ipsum, ad cupiditate doloremque accusantium molestias.
              </p>
              <button className=" bg-gradient-to-tr from-purple-500 to-indigo-800 text-white font-bold py-3 px-10 rounded-full hover:scale-110 hover:tranition-all duration-300 ease-in-out ">
                Read more
              </button>
            </div>

            <div className=" bg-gradient-to-tr from-purple-500 to-indigo-800 py-20 lg:flex lg:flex-row lg:w-1/2">
              <div className="mx-3 md:ml-40 md:h-80 md:w-80 lg:h-96 lg:w-96 lg:-ml-10">
                <Image src={shoes} width={"100%"} height={"100%"} />
              </div>

              <div className="px-3 md:pl-40 lg:pl-20">
                <h2 className="text-white font-bold text-3xl py-5">
                  Harum quidem
                </h2>
                <p className="text-gray-400 max-w-md pb-10">
                  Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                  Molestiae architecto, exercitationem, eaque dolores
                  reprehenderit explicabo ducimus illum et aliquam doloribus
                  repellendus, dignissimos omnis provident esse. Dicta,
                  architecto distinctio! Ut animi dolor excepturi vel nam
                  corporis placeat nihil quae consequatur optio! Accusamus earum
                  eaque quam fugiat.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className="bg-[url('../public/blue.svg')] bg-no-repeat bg-cover bg-center pb-20">
            <div className="md:text-center lg:flex lg:flex-row lg:justify-around">
              <div className="pt-20 ml-5">
                <h3 className="font-bold text-gray-300 text-xl py-3">
                  RERUM NECESSITATIBUS
                </h3>
                <h2 className="font-bold text-white text-3xl pb-5">
                  Temporibus ateum quibusadam
                </h2>
              </div>

              <div className="lg:pt-28">
                <button className="bg-yellow-400 text-white font-bold text-xl py-3 px-10 ml-5 rounded-full hover:scale-110 hover:tranition-all duration-300 ease-in-out">
                  Explore
                </button>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className="py-20">
            <div className="text-center pb-10">
              <h4 className="font-bold text-xl">SAEPE EVENIET</h4>
              <h2 className="font-bold text-3xl md:text-5xl">
                Voluptates repudiandae
              </h2>
            </div>

            <div className="flex flex-col lg:flex lg:flex-row lg:gap-10">
              <div className="mx-5 pb-20">
                <Image
                  src={boat}
                  width={"100%"}
                  height={"100%"}
                  className="pb-5"
                />
                <GiWineBottle className="text-5xl lg:text-7xl text-orange-600" />
                <h3 className="py-5 font-bold text-3xl">Consectetu</h3>
                <p className="text-gray-500">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Accusantium, dolores.
                </p>
              </div>

              <div className="mx-5 pb-20">
                <Image
                  src={plate}
                  width={"100%"}
                  height={"100%"}
                  className="pb-5"
                />
                <GiStarsStack className="text-5xl lg:text-7xl text-orange-600" />
                <h3 className="py-5 font-bold text-3xl">Consectetu</h3>
                <p className="text-gray-500">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Accusantium, dolores.
                </p>
              </div>

              <div className="mx-5 pb-10">
                <Image
                  src={bulb}
                  width={"100%"}
                  height={"100%"}
                  className="pb-5"
                />
                <FaUserAstronaut className="text-5xl lg:text-7xl text-orange-600" />
                <h3 className="py-5 font-bold text-3xl">Consectetu</h3>
                <p className="text-gray-500">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Accusantium, dolores.
                </p>
              </div>
            </div>
            <div className="mx-auto text-center py-10">
              <button className="text-xl font-bold text-purple-500 ring-2 rounded-full py-3 px-10 hover:scale-110 hover:tranition-all duration-300 ease-in-out">
                Load more
              </button>
            </div>
          </div>
        </section>

        <section className="bg-pink-50 py-20">
          <div className="flex flex-col lg:flex lg:flex-row lg:justify-between lg:mx-20">
            <div className=" bg-gradient-to-tl from-purple-500 to-indigo-800 lg:w-96 lg:h-80 shadow-2xl shadow-slate-800 mx-5 mb-20 md:mb-20 md:mx-auto ">
              <div className=" lg:w-96 lg:h-96 lg:ml-20 lg:mt-10">
                <Image src={image} width={"100%"} height={"100%"} />
              </div>
            </div>

            <div className="mx-5 max-w-3xl md:mx-20 lg:ml-40">
              <h3 className="font-bold">DOLORE EU FUGAIT</h3>
              <h2 className="font-bold text-3xl py-5 lg:text-5xl">
                Excepteur sint occaecat
              </h2>
              <p className="text-gray-500 leading-7">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni
                quos similique vitae enim suscipit dolorum repudiandae aut!
                Necessitatibus odit expedita fuga dicta, numquam ipsum deserunt
                enim esse? Itaque, illum voluptas.
              </p>

              <div className=" mt-5 lg:grid lg:grid-cols-2">

                <div className="flex mt-5">
                  <FaTruck className="text-3xl text-violet-500" />
                  <h3 className="text-xl font-bold pl-3 text-gray-600">
                    Cupidatan non
                  </h3>
                </div>

                <div className="flex mt-5">
                  <FaShoppingBag className="text-3xl text-violet-500" />
                  <h3 className="text-xl font-bold pl-3 text-gray-600">
                    Sunt in culpa
                  </h3>
                </div>

                <div className="flex mt-5">
                  <FiMonitor className="text-3xl text-violet-500" />
                  <h3 className="text-xl font-bold pl-3 text-gray-600">
                    Qui officia
                  </h3>
                </div>

                <div className="flex mt-5">
                  <FaWhmcs className="text-3xl text-violet-500" />
                  <h3 className="text-xl font-bold pl-3 text-gray-600">
                    Deserunt bollit
                  </h3>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className="py-20 flex flex-col lg:flex lg:flex-row lg:justify-around">
            <div className="mx-20">
              <h3 className="font-bold text-xl pl-3 lg:text-2xl">
                DOLORE EU FUGAIT
              </h3>
              <h2 className="font-bold text-3xl py-5 pl-3 lg:text-5xl">
                Veritatis
              </h2>
            </div>
            <div className="max-w-4xl font-medium text-gray-500 leading-7 p-3">
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Aspernatur blanditiis sint amet iusto quaerat quia asperiores ad
                doloremque ipsa! Impedit nobis optio aut voluptatibus sunt cum
                numquam nisi voluptate quae explicabo nam, cumque corporis minus
                ullam eius architecto sequi minima consectetur tenetur
                reprehenderit? Mollitia, id voluptatem natus officiis possimus
                tenetur?
              </p>
            </div>
          </div>

          <div className="flex flex-col pb-20 lg:flex lg:flex-row lg:justify-around lg:mx-auto">

            <div className="bg-[url('../public/ham.jpg')] bg-no-repeat bg-cover bg-center h-80 w-80 mx-auto mb-5">
              <div className="backdrop-brightness-50 w-full h-full">
                <h3 className="font-bold text-orange-400 text-xl pt-40 pl-5">
                  <FaHamburger className="text-3xl" />
                  Anim id eset laborum
                </h3>
              </div>
            </div>

            <div className="bg-[url('../public/sijalica.webp')] bg-no-repeat bg-cover bg-center h-80 w-80 mx-auto mb-5">
              <div className="backdrop-brightness-50 w-full h-full">
                <h3 className="font-bold text-red-500 text-xl pt-40 pl-5">
                  <FaLightbulb className="text-3xl" />
                  Anim id eset laborum
                </h3>
              </div>
            </div>

            <div className="bg-[url('../public/grana.webp')] bg-no-repeat bg-cover bg-center h-80 w-80 mx-auto mb-5">
              <div className="backdrop-brightness-50 w-full h-full">
                <h3 className="font-bold text-green-500 text-xl pt-40 pl-5">
                  <FaHandHoldingWater className="text-3xl" />
                  Anim id eset laborum
                </h3>
              </div>
            </div>

            <div className="bg-[url('../public/vet.jpg')] bg-no-repeat bg-cover bg-center h-80 w-80 mx-auto mb-5">
              <div className="backdrop-brightness-50 w-full h-full">
                <h3 className="font-bold text-blue-500 text-xl pt-40 pl-5">
                  <FaTruck className="text-3xl" />
                  Anim id eset laborum
                </h3>
              </div>
            </div>
          </div>
          <div className="mx-auto text-center py-20">
            <button className="text-xl font-bold text-blue-500 ring-2 rounded-full py-3 px-10 hover:scale-110 hover:tranition-all duration-300 ease-in-out">
              See all
            </button>
          </div>
        </section>

        <section>
          <div className="bg-[url('../public/bg2.svg')] bg-no-repeat bg-cover">
            <div className="text-center pt-20">
              <h3 className="font-bold text-xl text-white lg:text-2xl">
                EIUS MODI
              </h3>
              <h2 className="font-bold text-3xl text-white pt-3 lg:text-5xl">
                Tempora incidunt
              </h2>
            </div>

            <div className="py-20 flex justify-center">
              <div className=" bg-slate-100">
                <p className="font-medium text-gray-600 p-10 max-w-4xl">
                  "Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                  Laboriosam ullam eligendi perferendis velit porro atque
                  perspiciatis, dignissimos iste sit natus et praesentium at a
                  repudiandae. Aliquam ea quaerat nam veniam accusamus culpa
                  necessitatibus soluta numquam doloribus minus recusandae,
                  ipsam enim sit, animi molestiae incidunt beatae, aut omnis
                  explicabo alias. Nisi!"
                </p>

                <div className="flex flex-col items-center lg:flex lg:flex-row lg:justify-center">
                  <div className="w-1/3 h-1/3 pb-3 lg:w-1/6 lg:h-1/6 lg:pb-10">
                    <Image
                      src={woman}
                      width={"100%"}
                      height={"100%"}
                      className=" rounded-lg"
                    />
                  </div>
                  <div className="py-10 pl-5">
                    <h3 className="font-bold text-2xl">Davea Butler</h3>
                    <p className="font-bold text-xl">Voluptatum</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className="py-20">
            <div className=" mx-auto text-center">
              <h3 className="font-bold text-xl lg:text-2xl">UT LABORE ETE</h3>
              <h2 className="font-bold text-3xl pt-3 lg:text-5xl">
                Dolore magnam
              </h2>
            </div>

            <div className="py-10 mx-auto flex flex-col lg:flex lg:flex-row">
              <div className="mx-auto w-80 h-auto mb-10 pb-20 p-5 shadow-2xl shadow-slate-800">
                <p className="font-medium pt-5">June 10,2020</p>
                <h3 className="font-bold text-xl py-5 lg:text-3xl ">
                  Minus voluptatem voluptas ipsum vitae blanditiis laudantium.
                </h3>
                <p className="text-gray-500 pb-10">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Laudantium exercitationem soluta vero omnis cumque fugiat
                  aliquam rerum tempora debitis cum.
                </p>
                <FaChevronCircleRight className="text-5xl float-right text-orange-500" />
              </div>

              <div className="mx-auto w-80 h-auto mb-10 pb-20 p-5 shadow-2xl shadow-slate-800">
                <p className="font-medium pt-5">June 22,2020</p>
                <h3 className="font-bold text-xl py-5 lg:text-3xl ">
                  Greatar voluptatem voluptas vitae blanditiis laudantium.
                </h3>
                <p className="text-gray-500 pb-10">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Laudantium exercitationem soluta vero omnis cumque fugiat
                  aliquam rerum tempora debitis cum.
                </p>
                <FaChevronCircleRight className="text-5xl float-right text-orange-500" />
              </div>

              <div className="mx-auto w-80 h-auto mb-10 pb-20 p-5 shadow-2xl shadow-slate-800">
                <p className="font-medium pt-5">August 10,2020</p>
                <h3 className="font-bold text-xl py-5 lg:text-3xl ">
                  Consectetur adipisicing elit. Vero odio neque, Tempore.
                </h3>
                <p className="text-gray-500 pb-10">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Laudantium exercitationem soluta vero omnis cumque fugiat
                  aliquam rerum tempora debitis cum.
                </p>
                <FaChevronCircleRight className="text-5xl float-right text-orange-500" />
              </div>
              <div className="mx-auto w-80 h-auto mb-10 pb-20 p-5 shadow-2xl shadow-slate-800">
                <p className="font-medium pt-5">September 4,2020</p>
                <h3 className="font-bold text-xl py-5 lg:text-3xl ">
                  Tareus gunteres voluptas ipsum vitae blanditiis laudantium.
                </h3>
                <p className="text-gray-500 pb-10">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Laudantium exercitationem soluta vero omnis cumque fugiat
                  aliquam rerum tempora debitis cum.
                </p>
                <FaChevronCircleRight className="text-5xl float-right text-orange-500" />
              </div>
            </div>
          </div>
        </section>

        <section className="bg-[url('../public/blue.svg')] bg-no-repeat bg-cover">
          <div className="mx-auto py-10 flex flex-col lg:flex lg:flex-row">
            <div className="mx-5 w-70 py-10 md:mx-auto md:w-80">
              <h3 className="font-bold text-white text-xl lg:text-3xl">
                Est eligendi
              </h3>
              <p className="text-gray-400 pt-5">
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam,
                fugiat repudiandae illo consequatur saepe labore iste iusto
                molestias eligendi. Assumenda fugiat blanditiis, fugit enim
                praesentium nostrum nulla laboriosam itaque, ex aliquid corporis
                sapiente dignissimos iste optio consectetur quam ipsum id!
              </p>
            </div>

            <div className="mx-auto w-auto py-10">
              <h3 className="font-bold text-white text-xl lg:text-3xl">
                Temporibus
              </h3>
              <p className="text-white pt-5">Autem quibusdam</p>
              <p className="text-white pt-5">Et aut officias debitis</p>
              <p className="text-white pt-5">Aut rerum necessitatibus</p>
              <p className="text-white pt-5">Seape eneviet ut et</p>
            </div>

            <div className="mx-auto w-auto py-10">
              <p className="text-white pt-5">Itaquy erum rerat</p>
              <p className="text-white pt-5">Hic tenter a sapient</p>
              <p className="text-white pt-5">Voluptati mairoes alias</p>
              <p className="text-white pt-5">Perferdis dolorias</p>
            </div>

            <div className="mx-auto w-auto py-10">
              <h3 className="font-bold text-white text-xl lg:text-3xl">
                Sinet at
              </h3>

              <p className="text-gray-400 flex pt-5">
                <FaMapMarkerAlt className="text-2xl text-red-600" />
                Itaque erem rutar,43{" "}
              </p>
              <p className="text-gray-400 flex pt-5">
                <BsFillTelephoneForwardFill className="text-2xl text-green-600" />
                +1 212 3674 97
              </p>
              <p className="text-gray-400 flex pt-5">
                <AiFillMail className="text-2xl text-orange-600" />
                info@gamil.com
              </p>
            </div>
          </div>
          <hr class="mx-auto w-full h-1 bg-gray-300"></hr>

          <div className="py-10 flex flex-col lg:flex lg:flex-row">
            <div className="mx-auto pb-5">
              <p className="text-white text-xl">
                Copyright 2022.All Right reserved
              </p>
            </div>
            <div className="flex gap-8 mx-auto">
              <AiFillFacebook className="text-3xl text-blue-600 hover:scale-125 hover:transition-all duration-500 ease-in-out cursor-pointer" />
              <AiFillInstagram className="text-3xl text-orange-400 hover:scale-125 hover:transition-all duration-500 ease-in-out cursor-pointer" />
              <AiFillTwitterSquare className="text-3xl text-indigo-500 hover:scale-125 hover:transition-all duration-500 ease-in-out cursor-pointer" />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
